version: '3.3'
services:
  backend:
    build: ./backend
    secrets:
      - source: PRODUCTION_CONFIG
        target: /usr/src/api/strapi/config/environments/production/database.json
        uid: '103'
        gid: '103'
        mode: 0440

secrets:
  PRODUCTION_CONFIG:
    external: true