version: '3.3'
services:
  backend:
    build:
      context: ./backend
      args: 
        node_env: development
  frontend:
    build: 
      context: ./frontend
      args: 
        FRONTEND_ENV: development

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always

  redis:
    image: redis
    restart: always