version: '3.3'
services:
  backend:
    environment:
      - PORT=3000
      - JWT_SECRET=MyUltraSecurePassWordIWontForgetToChange
      - JWT_EXPIRATION=100d
      - MONGO_URI=mongodb://db:27017/myprojectdbname
      - EMAIL_FROM_NAME=My Project
      - EMAIL_FROM_ADDRESS=info@myproject.com
      - EMAIL_SMTP_DOMAIN_MAILGUN=myproject.com
      - EMAIL_SMTP_API_MAILGUN=123456
      - FRONTEND_URL=http://localhost:8080
      - USE_REDIS=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
